src/guide/urls.py
from django.urls import path
from guide import views

app_name="guide"

urlpatterns = [
    path("writer/", views.WriterList.as_view(), name="writer_list"), 
    path("writer/<int:pk>/", views.WriterDetail.as_view(), name="writer_detail"),
    path("writer/create/", views.WriterCreate.as_view(), name="writer_create"),
    path("writer/update/<int:pk>/", views.WriterUpdate.as_view(), name="writer_update"),
    path("writer/delete/<int:pk>/", views.WriterDelete.as_view(), name="writer_delete"),
    path("writer/search/<int:pk>/", views.WriterDetailFilter.as_view(), name="writer_search"),
    path("genre/", views.GenreList.as_view(), name="genre_list"), 
    path("genre/<int:pk>/", views.GenreDetail.as_view(), name="genre_detail"),
    path("genre/create/", views.GenreCreate.as_view(), name="genre_create"),
    path("genre/update/<int:pk>/", views.GenreUpdate.as_view(), name="genre_update"),
    path("genre/delete/<int:pk>/", views.GenreDelete.as_view(), name="genre_delete"),
    path("genre/search/<int:pk>/", views.GenreDetailFilter.as_view(), name="genre_search"),
    path("serie/", views.SerieList.as_view(), name="serie_list"), 
    path("serie/<int:pk>/", views.SerieDetail.as_view(), name="serie_detail"),
    path("serie/create/", views.SerieCreate.as_view(), name="serie_create"),
    path("serie/update/<int:pk>/", views.SerieUpdate.as_view(), name="serie_update"),
    path("serie/delete/<int:pk>/", views.SerieDelete.as_view(), name="serie_delete"),
    path("serie/search/<int:pk>/", views.SerieDetailFilter.as_view(), name="serie_search"),  
    path("publishing_house/", views.PublishingHouseList.as_view(), name="publishing_house_list"), 
    path("publishing_house/<int:pk>/", views.PublishingHouseDetail.as_view(), name="publishing_house_detail"),
    path("publishing_house/create/", views.PublishingHouseCreate.as_view(), name="publishing_house_create"),
    path("publishing_house/update/<int:pk>/", views.PublishingHouseUpdate.as_view(), name="publishing_house_update"),
    path("publishing_house/delete/<int:pk>/", views.PublishingHouseDelete.as_view(), name="publishing_house_delete"),
    path("publishing_house/search/<int:pk>/", views.PublishingHouseDetailFilter.as_view(), name="publishing_house_search"),

]

src/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("search/", views.search, name='q'),
    path('', views.view_home, name="home_page"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from comment import views as com_views


urlpatterns = [
    path('', include("home.urls")),
    path("admin/", admin.site.urls, name="admin"),
    path('account/', include('account.urls')),
    path('orders/', include("orders.urls", namespace ="orders"), name = "orders"),
    path("catalog/", include("catalog.urls", namespace ="catalog"), name = "catalog"),
    path("guide/", include("guide.urls", namespace ="guide"), name = "guide"),
    path('comment/', com_views.CommentCreate.as_view(), name="comment"),   
    
]+ static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/guide/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _



# Create your models here.
class Writer(models.Model):
    name = models.CharField(_("Автор"), max_length=100)
    discription = models.TextField(_("Описание"), max_length=3000, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Автора"
        verbose_name_plural = "Авторы"


class Serie(models.Model):
    name = models.CharField(_("Серия"), max_length=100)
    discription = models.TextField(_("Описание"), max_length=3000, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Серию"
        verbose_name_plural = "Серии"


class Genre(models.Model):
    name = models.CharField(_("Жанр"), max_length=100)
    discription = models.TextField(_("Описание"), max_length=3000, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class PublishingHouse(models.Model):
    name = models.CharField(_("Издательство"), max_length=100)
    discription = models.TextField(_("Описание"), max_length=3000, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Издательство"
        verbose_name_plural = "Издательства"

src/guide/forms.py
from django import forms
from . import models


class WriterModelForm(forms.ModelForm):
    class Meta:
        model = models.Writer
        fields = ("name", "discription")


class GenreModelForm(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = ("name", "discription")


class SerieModelForm(forms.ModelForm):
    class Meta:
        model = models.Serie
        fields = ("name", "discription")


class PublishingHouseModelForm(forms.ModelForm):
    class Meta:
        model = models.PublishingHouse
        fields = ("name", "discription")

src/guide/views.py
from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from . import models, forms
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy

# Create your views here.


class WriterDetail(DetailView):
    template_name = "guide/writer/writer_detail.html"
    model = models.Writer


class WriterDetailFilter(DetailView):
    template_name = "catalog/book_list_filter.html"
    model = models.Writer


class WriterList(ListView):
    template_name = "guide/writer/writer_list.html"
    paginate_by = 9
    model = models.Writer


class WriterCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = "guide/writer/writer_create.html"
    model = models.Writer
    form_class = forms.WriterModelForm
    success_url = reverse_lazy("guide:writer_list")
    login_url = "/account/login"
    permission_required = "guide.add_writer"


class WriterDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = "guide/writer/writer_delete.html"
    model = models.Writer
    success_url = reverse_lazy("guide:writer_list")
    login_url = "/account/login"
    permission_required = "guide.delete_writer"


class WriterUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = "guide/writer/writer_update.html"
    model = models.Writer
    form_class = forms.WriterModelForm
    success_url = reverse_lazy("guide:writer_list")
    login_url = "/account/login"
    permission_required = "guide.change_writer"


class GenreDetail(DetailView):
    template_name = "guide/genre/genre_detail.html"
    model = models.Genre


class GenreDetailFilter(DetailView):
    template_name = "catalog/book_list_filter.html"
    model = models.Genre


class GenreList(ListView):
    template_name = "guide/genre/genre_list.html"
    paginate_by = 9
    model = models.Genre


class GenreCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = "guide/genre/genre_create.html"
    model = models.Genre
    form_class = forms.GenreModelForm
    success_url = reverse_lazy("guide:genre_list")
    login_url = "/account/login"
    permission_required = "guide.add_genre"


class GenreDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = "guide/genre/genre_delete.html"
    model = models.Genre
    success_url = reverse_lazy("guide:genre_list")
    login_url = "/account/login"
    permission_required = "guide.delete_genre"


class GenreUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = "guide/genre/genre_update.html"
    model = models.Genre
    form_class = forms.GenreModelForm
    success_url = reverse_lazy("guide:genre_list")
    login_url = "/account/login"
    permission_required = "guide.change_genre"


class SerieDetail(DetailView):
    template_name = "guide/serie/serie_detail.html"
    model = models.Serie


class SerieDetailFilter(DetailView):
    template_name = "catalog/book_list_filter.html"
    model = models.Serie


class SerieList(ListView):
    template_name = "guide/serie/serie_list.html"
    paginate_by = 9
    model = models.Serie


class SerieCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = "guide/serie/serie_create.html"
    model = models.Serie
    form_class = forms.SerieModelForm
    success_url = reverse_lazy("guide:serie_list")
    login_url = "/account/login"
    permission_required = "guide.add_genre"


class SerieDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = "guide/serie/serie_delete.html"
    model = models.Serie
    success_url = reverse_lazy("guide:genre_list")
    login_url = "/account/login"
    permission_required = "guide.delete_genre"


class SerieUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = "guide/serie/serie_update.html"
    model = models.Serie
    form_class = forms.SerieModelForm
    success_url = reverse_lazy("guide:genre_list")
    login_url = "/account/login"
    permission_required = "guide.change_genre"


class PublishingHouseDetail(DetailView):
    template_name = "guide/publishing_house/publishing_house_detail.html"
    model = models.PublishingHouse


class PublishingHouseDetailFilter(DetailView):
    template_name = "catalog/book_list_filter.html"
    model = models.PublishingHouse


class PublishingHouseList(ListView):
    template_name = "guide/publishing_house/publishing_house_list.html"
    paginate_by = 9
    model = models.PublishingHouse


class PublishingHouseCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = "guide/publishing_house/publishing_house_create.html"
    model = models.PublishingHouse
    form_class = forms.PublishingHouseModelForm
    success_url = reverse_lazy("guide:publishing_house_list")
    login_url = "/account/login"
    permission_required = "guide.add_genre"


class PublishingHouseDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = "guide/publishing_house/publishing_house_delete.html"
    model = models.PublishingHouse
    success_url = reverse_lazy("guide:publishing_house_list")
    login_url = "/account/login"
    permission_required = "guide.delete_genre"


class PublishingHouseUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = "guide/publishing_house/publishing_house_update.html"
    model = models.PublishingHouse
    form_class = forms.PublishingHouseModelForm
    success_url = reverse_lazy("guide:publishing_house_list")
    login_url = "/account/login"
    permission_required = "guide.change_genre"

src/templates/guide/serie/serie_create.html
{% extends "base.html" %} 
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{%block title %}Osp_Book_Store{%endblock %}
{% block content %}
<div class="container text-center">
  <div class="row">
    <div class="col">
      **********
    </div>
  </div>
</div>
<hr>
<div class="container text-center">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
             <button type="submit" class="btn btn-outline-success my-2 my-sm-0 float-end">
                Создать
              </button>
            </form>
    </div>
    <div class="col-3"></div>
  </div>
</div>
{% endblock %}

src/templates/guide/serie/serie_delete.html
{% extends "base.html" %}
 {% load static %}
 {%block title%}Osp_Book_Store{%endblock %}
 {% block content %}
<div class="container text-center">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
<hr />
<div class="container text-center">
  <div class="row">
    <div class="col-3">
      <h1>{{object.name}}</h1>
    </div>
    <div class="col-6">{{ object.discription}}</div>
  </div>
  <div class="col-3">
  </div>
  <div class="row">
    <div class="col">
      <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-danger my-2 my-sm-0 float-end">Если уверен, то ЖМИ</button>
        </form>
    </div> 
  </div>
</div>
{% endblock %}

src/templates/guide/serie/serie_detail.html
{% extends "base.html" %}
 {% load static %}
 {%block title%}Osp_Book_Store{%endblock %}
 {% block content %}
<div class="container text-center">
  <div class="row">
    <div class="col">
      {% for obj in object.book_of_serie.all%}
        {{obj.title_of_the_book}}
        {{obj.writer}}
        {%endfor%}
    </div>
  </div>
</div>
<hr />
<div class="container text-center">
  <div class="row">
    <div class="col-3">
      <h1>{{object.name}}</h1>
    </div>
    <div class="col-6">{{ object.discription}}</div>
  </div>
  <div class="col-3">
  </div>
  <div class="row">
    <div class="col">
      {% if request.user|has_group:"MANAGERS" %} {% elif request.user|has_group:"ADMIN"%} 
      <a class="btn btn-outline-success my-2 my-sm-0 float-end" role="button" href="{% url 'guide:serie_update' pk=object.pk%}">Обновить</a>
      <a class="btn btn-outline-danger my-2 my-sm-0 float-end" role="button" href="{% url 'guide:serie_delete' pk=object.pk%}">Удалить</a>
      {% endif %}
    </div> 
  </div>
</div>
{% endblock %}

src/templates/guide/serie/serie_list.html
{% extends "base.html" %}
{% load static %}
{%block title %}Osp_Book_Store{% endblock %}
{% load group_tags %}
{% block content %}

<div class="container text-center">
  <div class=row>
    <div class=col> 
    </div>
  </div>
</div>
<div class="container">
    <table class="table caption-top">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Серии</th>
          </tr>
        </thead>
        <tbody>
        {% for obj in object_list %}
          <tr>
            <th scope="row">:)</th>
            <td><a href="{% url 'guide:serie_detail' pk=obj.pk%}"> {{obj.name}}</a></td>
            <td><a href="{% url 'guide:serie_search' pk=obj.pk%}" class="btn btn-outline-success my-2 my-sm-0 float-end" >
              Все книги данной серии
            </a></td>
            <!-- Кнопка-триггер модального окна -->
                <td><button type="button" class="btn btn-outline-success my-2 my-sm-0 float-end" data-bs-toggle="modal" data-bs-target="#{{ obj.pk}}">
                  Подробнее о серии
                </button></td>
                <!-- Модальное окно -->
                <div class="modal fade" id="{{ obj.pk}}" tabindex="-1" aria-labelledby="{{ obj.pk}}" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="{{ obj.pk}}">{{ obj.name}}</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                      </div>
                      <div class="modal-body">
                        ...{{ obj.discription}}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                      </div>
                    </div>
                  </div>
                </div>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      {% if request.user|has_group:"MANAGERS" %} {% elif request.user|has_group:"ADMIN"%} 
      <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="{% url 'guide:serie_create'%}">Добавить новую серию</a>
      {% endif %}
</div>
</div>
<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo В начало</a>
          <a href="?page={{ page_obj.previous_page_number }}">пред.</a>
      {% endif %}
      <span class="current">
          Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
      </span>
      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">след.</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">В конец. &raquo</a>
      {% endif %}
  </span>
</div>
{% endblock %}

src/templates/guide/serie/serie_update.html
{% extends "base.html" %} 
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{%block title %}Osp_Book_Store{%endblock %}
{% block content %}
<div class="container text-center">
  <div class="row">
    <div class="col">
      **********
    </div>
  </div>
</div>
<hr>
<div class="container text-center">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-success my-2 my-sm-0 float-end">
                Обновить
              </button>
        </form>
    </div>
    <div class="col-3"></div>
  </div>
</div>
{% endblock %}