src/catalog/urls.py
from django.urls import path
from catalog import views

app_name="catalog"

urlpatterns = [
    path("", views.BookList.as_view(), name="book_list"), 
    path("book/<int:pk>/", views.BookDetail.as_view(), name="book_detail"),
    path("book/create/", views.BookCreate.as_view(), name="book_create"),
    path("book/update/<int:pk>/", views.BookUpdate.as_view(), name="book_update"), 
    path("book/delete/<int:pk>/", views.BookDelete.as_view(), name="book_delete"), 
    path("book/<int:pk>/comment/", views.add_comment, name="add_comment"),
]

src/guide/urls.py
from django.urls import path
from guide import views

app_name="guide"

urlpatterns = [
    path("writer/", views.WriterList.as_view(), name="writer_list"), 
    path("writer/<int:pk>/", views.WriterDetail.as_view(), name="writer_detail"),
    path("writer/create/", views.WriterCreate.as_view(), name="writer_create"),
    path("writer/update/<int:pk>/", views.WriterUpdate.as_view(), name="writer_update"),
    path("writer/delete/<int:pk>/", views.WriterDelete.as_view(), name="writer_delete"),
    path("writer/search/<int:pk>/", views.WriterDetailFilter.as_view(), name="writer_search"),
    path("genre/", views.GenreList.as_view(), name="genre_list"), 
    path("genre/<int:pk>/", views.GenreDetail.as_view(), name="genre_detail"),
    path("genre/create/", views.GenreCreate.as_view(), name="genre_create"),
    path("genre/update/<int:pk>/", views.GenreUpdate.as_view(), name="genre_update"),
    path("genre/delete/<int:pk>/", views.GenreDelete.as_view(), name="genre_delete"),
    path("genre/search/<int:pk>/", views.GenreDetailFilter.as_view(), name="genre_search"),
    path("serie/", views.SerieList.as_view(), name="serie_list"), 
    path("serie/<int:pk>/", views.SerieDetail.as_view(), name="serie_detail"),
    path("serie/create/", views.SerieCreate.as_view(), name="serie_create"),
    path("serie/update/<int:pk>/", views.SerieUpdate.as_view(), name="serie_update"),
    path("serie/delete/<int:pk>/", views.SerieDelete.as_view(), name="serie_delete"),
    path("serie/search/<int:pk>/", views.SerieDetailFilter.as_view(), name="serie_search"),  
    path("publishing_house/", views.PublishingHouseList.as_view(), name="publishing_house_list"), 
    path("publishing_house/<int:pk>/", views.PublishingHouseDetail.as_view(), name="publishing_house_detail"),
    path("publishing_house/create/", views.PublishingHouseCreate.as_view(), name="publishing_house_create"),
    path("publishing_house/update/<int:pk>/", views.PublishingHouseUpdate.as_view(), name="publishing_house_update"),
    path("publishing_house/delete/<int:pk>/", views.PublishingHouseDelete.as_view(), name="publishing_house_delete"),
    path("publishing_house/search/<int:pk>/", views.PublishingHouseDetailFilter.as_view(), name="publishing_house_search"),

]

src/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("search/", views.search, name='q'),
    path('', views.view_home, name="home_page"),
]

src/orders/urls.py
from django.urls import path
from orders import views

app_name="orders"

urlpatterns = [
      path('cart/', views.CartDetailView.as_view(), name='cartview'), 
      path('cart-items-edit/', views.CartAddDeleteItemView.as_view(), name='cart-items-edit'), 
      path('create-order/', views.OrderCreateView.as_view(), name='create-order'), 
      path('done_order/', views.OrderSuccess.as_view(), name='done_order'), 
      path('order-update/<int:pk>', views.OrderUpdateView.as_view(), name='order-update'), 
      path('order-detail/<int:pk>', views.OrderDetailView.as_view(), name='order-detail'), 
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from comment import views as com_views


urlpatterns = [
    path('', include("home.urls")),
    path("admin/", admin.site.urls, name="admin"),
    path('account/', include('account.urls')),
    path('orders/', include("orders.urls", namespace ="orders"), name = "orders"),
    path("catalog/", include("catalog.urls", namespace ="catalog"), name = "catalog"),
    path("guide/", include("guide.urls", namespace ="guide"), name = "guide"),
    path('comment/', com_views.CommentCreate.as_view(), name="comment"),   
    
]+ static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/comment/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

# Create your models here.
class Comment(models.Model):
    name = models.CharField(_("Автор отзыва"), max_length=100)
    comment = models.TextField(_("Отзыв"), max_length=3000, blank=False, null=False)
    publish = models.DateTimeField(_("Дата внесения"), default=timezone.now)
    def __str__(self):
        return f"Автор комментария:({self.name}), Комментарий:{self.comment}"

src/comment/forms.py
from django import forms
from . import models


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ("name", "comment")

src/comment/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from . import models, forms
# Create your views here.
class CommentCreate(CreateView):
    template_name="comment/comment.html"
    model = models.Comment
    form_class = forms.CommentModelForm
    success_url = "/"

src/templates/base.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#712cf9">
        <link href={% static "/css/bootstrap.min.css" %} rel="stylesheet">
        <link href={% static "/css/sticky-footer-navbar.css" %} rel="stylesheet">
        <link href={% static "/css/main_style.css" %} rel="stylesheet">
        
        <title>{% block title %}{% endblock %}</title>
    
    </head>
    <body class="d-flex flex-column h-100">

        {% include "body.html" %}
        
        {% include "header.html" %}

    <main class="flex-shrink-0">
   
        {% block content %}{% endblock %}

    </main>
    {% include "messages.html" %}
    <hr>

        {% include "footer.html" %}
        <script src={% static 'jquery-3.3.1.slim.min.js' %}></script>
        <script src={% static 'popper.min.js' %}></script>
    <script src={% static "/js/bootstrap.bundle.min.js" %} ></script>
    <script src={% static "/js/color-modes.js" %} ></script>
    </body>
</html>

src/templates/body.html
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
      <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
      <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
      <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
      <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
  </svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
      <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
      <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
          Light
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
          Dark
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
          Auto
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
    </ul>
  </div>

src/templates/comment.html
{% extends "base.html" %} 
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{%block title %}Osp_Book_Store{%endblock %}
{% block content %}
<div class="container text-center">
  <div class="row">
    <div class="col">
      **********
    </div>
  </div>
</div>
<hr>
<div class="container text-center">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            {% if user.is_authenticated %}
            <button type="submit" class="btn btn-outline-success my-2 my-sm-0 float-end">
                Создать
              </button>
              {% endif %}
        </form>
    </div>
    <div class="col-3"></div>
  </div>
</div>
{% endblock %}

src/templates/footer.html
<footer class="footer mt-auto py-3 bg-body-tertiary">
    <div class="container text-center">
        <span class="text-body-secondary">© Osp_Book_Store 2023 Уполномоченный рассматривать обращения покупателей о нарушении их прав, предусмотренных законодательством о защите прав потребителей, телефон: +375(29)1234567, Email: admin@admin.by</span>
    </div>
</footer>

src/templates/header.html
<header>
    <!-- Fixed navbar -->
    
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="navbar-brand">
                        <a class="nav-link fs-2" aria-disabled="true" href="{% url 'home_page' %}">(::Osp_Book_Store::)</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link fs-5" aria-disabled="true" href="{% url 'catalog:book_list' %}">Книги</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link fs-5" aria-disabled="true" href="{% url 'guide:writer_list'%}">Авторы</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link fs-5" aria-disabled="true" href="{% url 'guide:genre_list' %}">Жанры</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link fs-5" aria-disabled="true" href="{% url 'guide:serie_list' %}">Серии</a>
                        </li>
                    <li class="nav-item">    
                        <a class="nav-link fs-5" aria-disabled="true" href="{% url 'guide:publishing_house_list' %}">Издательства</a>
                        </li>
                    </ul>
                <ul class="navbar-nav">
                    <li class="nav-item p-3">
                    <form class="d-flex" role="search" action="{% url 'q' %}" method="get">
                        <input class="form-control me-3" type="search" name="q" placeholder="Поиск" aria-label="Поиск"><br>
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                      </form> 
                    </li>   
                    <li class="nav-item p-3">
                    <div class="text-success">Пользователь: <br>{{ request.user }}</div>
                    </li>
                    <li class="nav-item p-3">
                    <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="{% url 'orders:cartview' %}">Корзина
                    <span class="badge text-bg-secondary">{{forloop.counter}}</span></a>
                    </li>
                    <li class="nav-item p-3">        
                {% if user.is_authenticated %}
                    <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="{% url 'logout'%}?next={{request.path}}">Выйти</a>
                {% else %}
                    <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="{% url 'login'%}?next={{request.path}}">Войти</a>
                {% endif %}
                    </li>
                    <li class="nav-item p-3">
                    {% if user.is_superuser %}
                    <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="/admin">ADMIN</a>
                    {% endif %}
                    </li>
                </ul>        
            </div>
        </div>
    </nav>
</header>

src/templates/main.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Osp_Book_Store{% endblock %}
{% block content %}

<div class="container text-center ">
  <div class="row align-items-center">
    <div class="col-2">
      <img class="mb-4" src={% static "nerd_face_1024.gif" %} alt="" width="150" height="150">
    </div>
    <div class="col auto">
        <p class="text-warning bg-dark fs-5">«Osp_Book_Store» является крупной торговой сетью в РБ. В фирменном книжном магазине сети предлагается большой выбор разнообразной литературы и периодических изданий:
художественная литература в различных жанрах;
детская литература;
учебная литература, методические пособия;
научно-популярные издания;
литература о хобби, творчестве;
коллекционные издания и др.</p>
    </div>
    <div class="col-2">
      <img class="mb-4" src={% static "logo.png" %} alt="" width="150" height="150">
    </div>
  </div>
</div>

<div class="container">
<marquee behavior="alternate" direction="left" >
  <h1>#Очень рад Вас видеть /{{ request.user }}/ на своем сайте!# <br>
    {% if user.is_authenticated %}
  Спасибо, что зарегистрировались:)</h1>
  {% endif %}
</marquee>
</div>
<div class="container">
  <div class="row">
    <div class="col-6">
      <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="4000">
            <img src="{% static "bootstrap.jpg" %}" class="d-block w-100" alt="..." height="200">
          </div>
          <div class="carousel-item" data-bs-interval="4000">
            <img src="{% static "html_css.png" %}" class="d-block w-100" alt="..." height="200">
          </div>
        </div>
      </div>
    </div>
    <div class="col-6">
      <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="4000">
            <img src="{% static "it.png" %}" class="d-block w-100" alt="..." height="200">
          </div>
          <div class="carousel-item" data-bs-interval="4000">
            <img src="{% static "python_django.webp" %}" class="d-block w-100" alt="..." height="200">
          </div>
        </div>
        </div>
   </div>
</div>
<hr>
<div class="container px-4">
  <div class=row gx-5>
    <div class=col> 
      <div class="p-3" >
        <h3>НОВИНКИ 2023 :</h3> </div>
    </div>
  </div>
</div>
<div class="align-self-stretch">
  <div class=row>
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
    {% for obj in new_list %}
      <div class="col d-flex align-items-stretch">
        <div class="card">
        <img src="{{obj.cover_foto.url}}" class="card-img-top" alt="..." height="350">
          <div class="card-body">
          <h4 class="card-title"><a href="/catalog/book/{{ obj.pk}}"> {{obj.title_of_the_book}}</a></h4>
          <p class="card-text">Стоимость:&nbsp;&nbsp;{{obj.price}}</p>
          </div>
          <form  class=" p-4 float-end" action="/cart" method="get">
            Количество:
            <input type="number" name="quantity" min="1" value="1">
            <input type="hidden" name="product" value="{{object.pk}}">
            <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">В КОРЗИНУ</button>
            </form>
        </div> 
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<hr>
<div class="container px-4">
  <div class=row gx-5>
    <div class=col> 
      <div class="p-3" ><h3>С ВЫСОКИМ РЭЙТИНГОМ :</h3> </div>
    </div>
  </div>
</div>
<div class="align-self-stretch">
  <div class=row>
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
    {% for obj in rating_list %}
      <div class="col d-flex align-items-stretch">
        <div class="card">
        <img src="{{obj.cover_foto.url}}" class="card-img-top" alt="..." height="350">
          <div class="card-body">
          <h4 class="card-title"><a href="/catalog/book/{{ obj.pk}}"> {{obj.title_of_the_book}}</a></h4>
          <p class="card-text">Стоимость:&nbsp;&nbsp;{{obj.price}}</p>
          </div>
          <form  class=" p-4 float-end" action="/cart" method="get">
            Количество:
            <input type="number" name="quantity" min="1" value="1">
            <input type="hidden" name="product" value="{{object.pk}}">
            <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">В КОРЗИНУ</button>
            </form>
        </div> 
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<hr>
<div class="container px-4">
  <div class=row gx-5>
    <div class=col> 
      <div class="p-4" ><h3>НОВЫЕ ПОСТУПЛЕНИЯ :</h3></div>
    </div>
  </div>
</div>

<div class="align-self-stretch">
  <div class=row >
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
    {% for obj in last_list %}
      <div class="col d-flex align-items-stretch">
        <div class="card">
        <img src="{{obj.cover_foto.url}}" class="card-img-top" alt="..." height="350">
          <div class="card-body">
          <h4 class="card-title"><a href="/catalog/book/{{ obj.pk}}"> {{obj.title_of_the_book}}</a></h4>
          <p class="card-text">Стоимость:&nbsp;&nbsp;{{obj.price}}</p>
          </div>
          <form  class=" p-4 float-end" action="/cart" method="get">
            Количество:
            <input type="number" name="quantity" min="1" value="1">
            <input type="hidden" name="product" value="{{object.pk}}">
            <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">В КОРЗИНУ</button>
            </form>
          </div> 
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>
<hr>
<div class="container text-center ">
  <div class=row gx-5>
    <div class=col> 
      <div class="p-3" ><h3>Уважаемый Покупатель, здесь Вы можете оставить отзыв на хорошую работу магазина или указать на недостатки и помочь нам стать лучше.</h3>
        <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="/comment">Добавить отзыв</a>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="container">
  <div class="row">
        {% for obj in comment_list %}
        <div class="col-4">
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">Автор:</label>
          <h2>{{obj.name}}</h2>
        </div>
        <div class="mb-3">
          <label for="exampleFormControlTextarea1" class="form-label">Отзыв:</label>
          <p>{{obj.comment}}</p>
        </div>
      </div>
        {% endfor %}
        
    </div>
</div>
<hr>
<div class="container text-center">
  <div class="row align-items-center">
    <div class="col-2">
      <div class="card border-success mb-1" style="max-width: 20rem;">
        <div class="card-header bg-transparent border-success">Информация</div>
        <div class="card-body text-success">
          <ul>
            <li class="fs-8"><a href="#" data-bs-toggle="modal" data-bs-target="#delivery">О доставке</a></li>
            <li class="fs-6"><a href="#" data-bs-toggle="modal" data-bs-target="#rights">Права потребителя</a></li>
            <li class="fs-6"><a href="#" data-bs-toggle="modal" data-bs-target="#refund">Возврат товара</a></li>
        </ul>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card border-success mb-1">
        <div class="card-header bg-transparent border-success">Информация</div>

        <iframe src="https://www.nbrb.by/statistics/rates/banner.asp?lan=ru&datatype=1
        &fnt=Tahoma, Arial&fntsize=21.5px&fntcolor=black
        &lnkcolor=seagreen&bgcolor=white&brdcolor=white"
        width=100%  scrolling=no frameborder=0 style="margin: 0 50px 0 0;"></iframe>

      </div>
    </div>
    <div class="col-4">
      <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="5000">
            <img src="{% static "slide2.jpg" %}" class="d-block w-100" alt="..." height="200">
          </div>
          <div class="carousel-item" data-bs-interval="5000">
            <img src="{% static "slide3.webp" %}" class="d-block w-100" alt="..." height="200">
          </div>
          <div class="carousel-item" data-bs-interval="5000">
            <img src="{% static "slide4.png" %}" class="d-block w-100" alt="..." height="200">
          </div>
        </div>
    </div>
  </div>
    <div class="col-2">
      <div class="card border-success mb-1" style="max-width: 20rem;">
        <div class="card-header bg-transparent border-success">Информация</div>
        <div class="card-header bg-transparent border-success">
        <div class="fb-like" data-share="true" data-width="300" data-show-faces="true">&nbsp;</div>
        <div class="banner-title">Бесплатный самовывоз</div>
        <div class="banner-content">Почтой бесплатно</div>
        <div class="banner-content">от 100 руб.</div>

        </div>
    </div>
  </div>

  <!-- Модальное окно -->
  {% include "info.html" %}
</div>
{% endblock %}

src/templates/messages.html
{% if messages %}
{% for message in messages %}
    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
        <i class="fas fa-info-circle"></i> {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% endif %}